# BMAD Core Configuration
# This file contains core settings that apply to all agents

# Development Standards
developmentStandards:
  es6Modules:
    mandatory: true
    rules:
      - "ALL JavaScript files MUST use ES6 module syntax (export/import)"
      - "ALL classes MUST have 'export' keyword"
      - "ALL dependencies MUST use 'import' with .js extension"
      - "NEVER use global window objects for class definitions"
      - "ALWAYS include .js extension in import paths"
      - "HTML scripts MUST have type='module' attribute"

# Agent Load Always Files
devLoadAlwaysFiles:
  - "PROJECT_STANDARDS.md"
  - ".bmad-core/core-config.yaml"

# Project Standards Reference
projectStandardsFile: "PROJECT_STANDARDS.md"
